#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common
source scripts/version

SOURCEDIR=${BUILD}/${VERSION}
while [ "$#" -gt 0 ]; do
    case $1 in
        --srcdir)
            shift 1
            SOURCEDIR="$1"
            ;;
        *)
            break
            ;;
    esac
    shift 1
done


export CCACHE_DIR="${HOME}/.kernel-ccache"
export CC="ccache gcc"
export PATH="/usr/lib/ccache:$PATH"
KERNEL=$(basename ${KERNEL_URL})
FIRMWARE=$(readlink -f scripts/firmware)
MODULE_LIST=$(readlink -f modules.list)
MODULE_EXTRA_LIST=$(readlink -f modules-extra.list)

if [ -e "/source/dist/kernel/linux-${KERNEL_VERSION}-x86.tar.gz" ]; then
	echo "skipping kernel build - found linux-${KERNEL_VERSION}-rancher-x86.tar.gz in ./dist/kernel/"
else
	cd ${SOURCEDIR}
	make oldconfig
	KVER=$(make kernelrelease)
	if [ -e "linux-${KERNEL_VERSION}-x86.tar" ] \
	   && [ "$KVER" == "$KERNEL_VERSION" ]; then
		echo "Skipping kernel build, found linux-${KERNEL_VERSION}-x86.tar in $(pwd)"
	else
		echo "building $KVER"
		make -j$(nproc) tar-pkg
	fi
fi
