#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common

export CCACHE_DIR="${HOME}/.kernel-ccache"
export CC="ccache gcc"
export PATH="/usr/lib/ccache:$PATH"
KERNEL=$(basename ${KERNEL_URL})
DIR=${KERNEL/.tar.*//}
FIRMWARE=$(readlink -f scripts/firmware)

cd ${BUILD}/${DIR}

# TODO update config/kernel-config for the latest kernel
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) tar-pkg

create_firmware_tar $FIRMWARE

mkdir -p ${DIST}/kernel

FILE=$(echo linux*.tar)
tar --concatenate --file=${FILE} firmware.tar
cat $FILE | gzip -c > ${DIST}/kernel/${FILE}.gz
list_build_files | tar -czf ${DIST}/kernel/build.tar.gz -T /dev/stdin
