#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common
source scripts/version

export CCACHE_DIR="${HOME}/.kernel-ccache"
export CC="ccache gcc"
export PATH="/usr/lib/ccache:$PATH"
KERNEL=$(basename ${KERNEL_URL})
DIR=${VERSION}
FIRMWARE=$(readlink -f scripts/firmware)
MODULE_LIST=$(readlink -f modules.list)
MODULE_EXTRA_LIST=$(readlink -f modules-extra.list)

cd ${BUILD}/${DIR}

make oldconfig
make -j$(nproc) tar-pkg
