#!/bin/bash
set -e

cd $(dirname $0)/..

./scripts/download
./scripts/extract
./scripts/build-kernel
./scripts/package-kernel
./scripts/build-images

echo
echo "--- ${KERNEL_VERSION} Kernel prepared for RancherOS"
echo "	./dist/kernel/extra-linux-${KERNEL_VERSION}-x86.tar.gz"
echo "	./dist/kernel/build-linux-${KERNEL_VERSION}-x86.tar.gz"
echo "	./dist/kernel/linux-${KERNEL_VERSION}-x86.tar.gz"
echo "	./dist/kernel/config"
echo
echo "Images ready to push:"
cat dist/images
echo
