#!/bin/bash
set -e

cd $(dirname $0)/..

./scripts/test-firmware

if ! ./scripts/download; then
	echo "blah"
	exit 1
fi
./scripts/extract
run-parts -v ./scripts/hooks
./scripts/build-kernel
./scripts/package-kernel
./scripts/build-images

