#!/bin/bash
set -e

cd $(dirname $0)/..
if ! ./scripts/download; then
    echo "blah"
    exit 1
fi

./scripts/extract
run-parts -v ./scripts/hooks

source scripts/build-common
source scripts/version

DIR=${VERSION}

if [ -e "/source/dist/kernel/linux-${KERNEL_VERSION}-${KERNEL_ARCH}.tar.gz" ]; then
    echo "skipping kernel build - found linux-${KERNEL_VERSION}-rancher-${KERNEL_ARCH}.tar.gz in ./dist/kernel/"
else
    cd ${BUILD}/${DIR}
    make ARCH=${KERNEL_ARCH} oldconfig
    cp .config ${DIST}/kernel/config
fi
