#!/bin/bash
set -e
set -x

cd $(dirname $0)/..

: ${ARTIFACTS:=$(pwd)/assets}

check()
{
    local hash=$1
    local file=$2

    if [ ! -e "$file" ]; then
        return 1
    fi

    CURRENT=$(sha1sum $file | awk '{print $1}')

    [ "$hash" = "$CURRENT" ]
}

download()
{
    mkdir -p ${ARTIFACTS}

    local url=$2
    local file=${ARTIFACTS}/$(basename $2)
    local hash=$1

    if ! check $hash $file; then
        curl -sL $url > $file
    fi

    if ! check $hash $file; then
        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
        return 1
    fi
}

download 84b9bc53bbb4dd465b97ea54a71a9805e27ae4f2 https://github.com/rancher/linux/archive/Ubuntu-3.19.0-27.29.tar.gz
