#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common
source scripts/version

KERNEL=$(basename ${KERNEL_URL})
DIR=${VERSION}

mkdir -p ${BUILD}
cd ${BUILD}

if [ ! -e ${DIR} ]; then
    echo Extracting ${ARTIFACTS}/${KERNEL}
    TEMP=$(mktemp -d -p ${BUILD})
    mkdir ${TEMP}/${DIR}
    trap "rm -rf ${TEMP}" exit

    ls -lah ${ARTIFACTS}/${KERNEL}
    tar xf ${ARTIFACTS}/${KERNEL} -C ${TEMP}/${DIR} --strip-components=1
    mv ${TEMP}/${DIR} ${DIR}
fi

cp ${CONFIG}/kernel-config ${DIR}/.config
