#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/build-common
source scripts/version

SOURCEDIR=${BUILD}/${VERSION}
while [ "$#" -gt 0 ]; do
    case $1 in
        --srcdir)
            shift 1
            SOURCEDIR="$1"
            ;;
        *)
            break
            ;;
    esac
    shift 1
done



export CCACHE_DIR="${HOME}/.kernel-ccache"
export CC="ccache gcc"
export PATH="/usr/lib/ccache:$PATH"
KERNEL=$(basename ${KERNEL_URL})
FIRMWARE=$(readlink -f scripts/firmware)
MODULE_LIST=$(readlink -f modules.list)
MODULE_EXTRA_LIST=$(readlink -f modules-extra.list)

cd ${SOURCEDIR}

create_firmware_tar $FIRMWARE

mkdir -p ${DIST}/kernel

FILE=$(echo linux*.tar)

(
    split_tar $FILE $MODULE_LIST $MODULE_EXTRA_LIST
)

tar --concatenate --file=base.tar firmware.tar
tar --concatenate --file=extra.tar firmware-extra.tar
cat base.tar | gzip -c > ${DIST}/kernel/${FILE}.gz
cat extra.tar | gzip -c > ${DIST}/kernel/extra.tar.gz
list_build_files | tar -czf ${DIST}/kernel/build.tar.gz -T /dev/stdin
